name = "Infomaniak"
npm = "@ai-sdk/openai-compatible"
api = "https://api.infomaniak.com/2/ai/${INFOMANIAK_PROJECT_ID}/openai/v1"
env = ["INFOMANIAK_API_KEY", "INFOMANIAK_PROJECT_ID"]
doc = "https://developer.infomaniak.com/docs/api/get/1/ai/models"
